/**
 * HomEasy Canonical Real Estate & Hospitality Amenities Catalog
 *
 * Professional ontology inspired by Airbnb Plus, Booking.com, and Zillow,
 * tailored specifically for Cambodia (Siem Reap & Phnom Penh).
 */

export interface AmenityDefinition {
  id: string;
  nameEn: string;
  nameKh: string;
  nameRu: string;
  category: 'appliances' | 'power' | 'security' | 'outdoor' | 'parking' | 'services' | 'views';
  icon: string;
  isFilterable: boolean; // Suitable as a pill filter in Telegram Mini App
}

export const CANONICAL_AMENITIES: AmenityDefinition[] = [
  // ── 1. Power & Critical Cambodian Infrastructure ──────────────────────────
  {
    id: 'backup_generator',
    nameEn: 'Backup Generator',
    nameKh: 'ម៉ាស៊ីនភ្លើងបម្រុង',
    nameRu: 'Резервный генератор',
    category: 'power',
    icon: '⚡',
    isFilterable: true,
  },
  {
    id: 'solar_power',
    nameEn: 'Solar Power',
    nameKh: 'ថាមពលពន្លឺព្រះអាទិត្យ',
    nameRu: 'Солнечные батареи',
    category: 'power',
    icon: '☀️',
    isFilterable: false,
  },
  {
    id: 'elevator',
    nameEn: 'Elevator / Lift',
    nameKh: 'ជណ្តើរយន្ត',
    nameRu: 'Лифт',
    category: 'power',
    icon: '🛗',
    isFilterable: true,
  },
  {
    id: 'water_filtration',
    nameEn: 'Drinking Water Filtration',
    nameKh: 'ប្រព័ន្ធចម្រោះទឹកស្អាត',
    nameRu: 'Фильтрация питьевой воды',
    category: 'power',
    icon: '🚰',
    isFilterable: false,
  },

  // ── 2. Comfort & Climate Control ──────────────────────────────────────────
  {
    id: 'ac_all_rooms',
    nameEn: 'Air Conditioning (All Rooms)',
    nameKh: 'ម៉ាស៊ីនត្រជាក់គ្រប់បន្ទប់',
    nameRu: 'Кондиционеры во всех комнатах',
    category: 'appliances',
    icon: '❄️',
    isFilterable: true,
  },
  {
    id: 'ceiling_fan',
    nameEn: 'Ceiling Fans',
    nameKh: 'កង្ហារពិដាន',
    nameRu: 'Потолочные вентиляторы',
    category: 'appliances',
    icon: '🌀',
    isFilterable: false,
  },
  {
    id: 'hot_water_heater',
    nameEn: 'Hot Water (Heater)',
    nameKh: 'ម៉ាស៊ីនទឹកក្តៅ',
    nameRu: 'Водонагреватель (горячая вода)',
    category: 'appliances',
    icon: '🚿',
    isFilterable: true,
  },
  {
    id: 'bathtub',
    nameEn: 'Bathtub',
    nameKh: 'អាងងូតទឹក',
    nameRu: 'Ванна',
    category: 'appliances',
    icon: '🛁',
    isFilterable: true,
  },

  // ── 3. Kitchen & Household Appliances ─────────────────────────────────────
  {
    id: 'washing_machine',
    nameEn: 'Washing Machine',
    nameKh: 'ម៉ាស៊ីនបោកខោអាវ',
    nameRu: 'Стиральная машина',
    category: 'appliances',
    icon: '🧺',
    isFilterable: true,
  },
  {
    id: 'clothes_dryer',
    nameEn: 'Clothes Dryer',
    nameKh: 'ម៉ាស៊ីនសម្ងួតសម្លៀកបំពាក់',
    nameRu: 'Сушильная машина',
    category: 'appliances',
    icon: '💨',
    isFilterable: false,
  },
  {
    id: 'western_kitchen',
    nameEn: 'Western Kitchen',
    nameKh: 'ចង្ក្រានបាយបែបបស្ចិមប្រទេស',
    nameRu: 'Европейская кухня',
    category: 'appliances',
    icon: '🍳',
    isFilterable: true,
  },
  {
    id: 'refrigerator',
    nameEn: 'Refrigerator / Fridge',
    nameKh: 'ទូទឹកកក',
    nameRu: 'Холодильник',
    category: 'appliances',
    icon: '🧊',
    isFilterable: false,
  },
  {
    id: 'microwave',
    nameEn: 'Microwave',
    nameKh: 'ម៉ាស៊ីនកម្តៅម្ហូប',
    nameRu: 'Микроволновка',
    category: 'appliances',
    icon: '📻',
    isFilterable: false,
  },
  {
    id: 'oven',
    nameEn: 'Oven',
    nameKh: 'ឡដុតនំ',
    nameRu: 'Духовой шкаф',
    category: 'appliances',
    icon: '🔥',
    isFilterable: false,
  },
  {
    id: 'smart_tv',
    nameEn: 'Smart TV',
    nameKh: 'ទូរទស្សន៍វៃឆ្លាត',
    nameRu: 'Смарт ТВ',
    category: 'appliances',
    icon: '📺',
    isFilterable: false,
  },
  {
    id: 'work_desk',
    nameEn: 'Work Desk / Workspace',
    nameKh: 'តុធ្វើការ',
    nameRu: 'Рабочее место / стол',
    category: 'appliances',
    icon: '💻',
    isFilterable: true,
  },

  // ── 4. Outdoor, Building & Leisure ────────────────────────────────────────
  {
    id: 'swimming_pool',
    nameEn: 'Swimming Pool',
    nameKh: 'អាងហែលទឹក',
    nameRu: 'Бассейн',
    category: 'outdoor',
    icon: '🏊‍♂️',
    isFilterable: true,
  },
  {
    id: 'balcony',
    nameEn: 'Balcony',
    nameKh: 'យ៉រ',
    nameRu: 'Балкон',
    category: 'outdoor',
    icon: '🌿',
    isFilterable: true,
  },
  {
    id: 'private_terrace',
    nameEn: 'Private Terrace / Rooftop',
    nameKh: 'ដំបូលខាងលើ',
    nameRu: 'Терраса / Руфтоп',
    category: 'outdoor',
    icon: '🌇',
    isFilterable: false,
  },
  {
    id: 'garden',
    nameEn: 'Garden / Green Yard',
    nameKh: 'សួនច្បារ',
    nameRu: 'Сад / Зеленый двор',
    category: 'outdoor',
    icon: '🌳',
    isFilterable: true,
  },
  {
    id: 'gym',
    nameEn: 'Gym / Fitness Room',
    nameKh: 'បន្ទប់ហាត់ប្រាណ',
    nameRu: 'Спортзал',
    category: 'outdoor',
    icon: '🏋️‍♂️',
    isFilterable: true,
  },
  {
    id: 'bbq_area',
    nameEn: 'BBQ Area',
    nameKh: 'កន្លែងអាំងសាច់',
    nameRu: 'Зона барбекю',
    category: 'outdoor',
    icon: '🍖',
    isFilterable: false,
  },

  // ── 5. Security & Community ───────────────────────────────────────────────
  {
    id: 'security_24_7',
    nameEn: '24/7 Security Guard',
    nameKh: 'សន្តិសុខ 24 ម៉ោង',
    nameRu: 'Охрана 24/7',
    category: 'security',
    icon: '👮‍♂️',
    isFilterable: true,
  },
  {
    id: 'cctv',
    nameEn: 'CCTV Surveillance',
    nameKh: 'កាមេរ៉ាសុវត្ថិភាព',
    nameRu: 'Видеонаблюдение (CCTV)',
    category: 'security',
    icon: '📹',
    isFilterable: false,
  },
  {
    id: 'gated_borey',
    nameEn: 'Gated Community (Borey)',
    nameKh: 'បុរីមានរបងសុវត្ថិភាព',
    nameRu: 'Закрытый поселок (Борей)',
    category: 'security',
    icon: '🏘️',
    isFilterable: true,
  },
  {
    id: 'keycard_access',
    nameEn: 'Keycard / Smart Lock',
    nameKh: 'សោរឆ្លាតវៃ',
    nameRu: 'Электронный замок / смарт-ключ',
    category: 'security',
    icon: '💳',
    isFilterable: false,
  },

  // ── 6. Parking ────────────────────────────────────────────────────────────
  {
    id: 'car_parking',
    nameEn: 'Car Parking (Covered / Secure)',
    nameKh: 'ចំណតរថយន្ត',
    nameRu: 'Парковка для авто',
    category: 'parking',
    icon: '🚗',
    isFilterable: true,
  },
  {
    id: 'motorbike_parking',
    nameEn: 'Motorbike Parking',
    nameKh: 'ចំណតម៉ូតូ',
    nameRu: 'Парковка для байков',
    category: 'parking',
    icon: '🛵',
    isFilterable: false,
  },

  // ── 7. Services & Inclusions ──────────────────────────────────────────────
  {
    id: 'free_wifi',
    nameEn: 'Free High-Speed WiFi',
    nameKh: 'អ៊ីនធឺណិតឥតគិតថ្លៃ',
    nameRu: 'Бесплатный Wi-Fi',
    category: 'services',
    icon: '📶',
    isFilterable: true,
  },
  {
    id: 'cleaning_included',
    nameEn: 'Cleaning Service Included',
    nameKh: 'សេវាសម្អាត',
    nameRu: 'Уборка включена',
    category: 'services',
    icon: '🧹',
    isFilterable: true,
  },
  {
    id: 'garbage_free',
    nameEn: 'Free Garbage Collection',
    nameKh: 'ថ្លៃសំរាមឥតគិតថ្លៃ',
    nameRu: 'Вывоз мусора включен',
    category: 'services',
    icon: '🗑️',
    isFilterable: false,
  },
  {
    id: 'linen_change',
    nameEn: 'Bed Linen Change',
    nameKh: 'ផ្លាស់ប្តូរកម្រាលពូក',
    nameRu: 'Смена постельного белья',
    category: 'services',
    icon: '🛏️',
    isFilterable: false,
  },

  // ── 8. Views & Living Ambience ────────────────────────────────────────────
  {
    id: 'river_view',
    nameEn: 'River View',
    nameKh: 'ទេសភាពមាត់ស្ទឹង',
    nameRu: 'Вид на реку',
    category: 'views',
    icon: '🌊',
    isFilterable: true,
  },
  {
    id: 'pool_view',
    nameEn: 'Pool View',
    nameKh: 'ទេសភាពអាងហែលទឹក',
    nameRu: 'Вид на бассейн',
    category: 'views',
    icon: '🏊',
    isFilterable: false,
  },
  {
    id: 'city_view',
    nameEn: 'City View',
    nameKh: 'ទេសភាពទីក្រុង',
    nameRu: 'Вид на город',
    category: 'views',
    icon: '🏙️',
    isFilterable: false,
  },
];

